[package]
name = "nimbus-cli"
description = """Run one command or open an interactive REPL to manage and sync objects in vaults. \
A vault is a filesystem-like tree that stores metadata plus a way to reach the object, so one can \
be backed by an API, your own filesystem, a shell command, or another vault."""
readme = "README.md"
documentation = "https://docs.rs/nimbus-cli"
keywords = ["nimbus", "sync", "vault", "cli", "repl"]
categories = ["command-line-utilities", "filesystem"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap.workspace = true
tokio.workspace = true
nimbus-core = { version = "0.2.0", path = "../core/" }
nimbus-creator = { version = "0.2.0", path = "../creator/" }
ratatui.workspace = true
anyhow.workspace = true
rustyline = "18.0.1"
